//! `christen route` — discovers systemd launch sites and generates drop-in
//! files that rewrite each `ExecStart` to route through `agentns-claude`.
//!
//! # Design contract
//! - [`render_dropin`] is **pure**: it makes zero filesystem calls and returns
//!   a [`DropIn`] value.
//! - [`SystemdSource`] does filesystem I/O (scan + read unit files); it
//!   implements [`LaunchSiteSource`].
//! - The `apply` logic in [`apply_route`] writes files and **prints** (never
//!   runs) the `systemctl` reload/restart lines.

use std::fs;
use std::path::{Path, PathBuf};

use crate::config::ChristenConfig;
use crate::model::{RawSite, RouteAction, RoutePlan, SiteKind};
use crate::source::{LaunchSiteSource, SourceError};

// ── Drop-in value type ────────────────────────────────────────────────────────

/// A rendered systemd drop-in override: path it should be written to and
/// the INI content (with the mandatory clear-then-set `ExecStart=` pair).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropIn {
    /// Destination path: `~/.config/systemd/user/<unit>.d/10-christen.conf`.
    pub path: PathBuf,
    /// Full INI content of the drop-in file.
    pub contents: String,
}

// ── Pure renderer ─────────────────────────────────────────────────────────────

/// Renders a drop-in override for a single systemd unit.
///
/// The output uses the mandatory clear-then-set pattern:
/// ```ini
/// [Service]
/// ExecStart=
/// ExecStart=/path/to/agentns-claude --intent /build ... -- /original
/// ```
///
/// **Pure**: makes zero filesystem calls.
///
/// # Parameters
/// - `systemd_dir` — base directory (e.g. `~/.config/systemd/user`); used to
///   form the drop-in path.
/// - `unit` — unit filename (e.g. `claude-build.service`).
/// - `exec_start` — the original `ExecStart=` value from the unit.
/// - `intent` — intent tag (e.g. `/build`).
/// - `budget` — budget string (e.g. `wall=7200s,fork=2000`).
#[must_use]
pub fn render_dropin(
    systemd_dir: &Path,
    unit: &str,
    exec_start: &str,
    intent: &str,
    budget: &str,
) -> DropIn {
    let path = systemd_dir
        .join(format!("{unit}.d"))
        .join("10-christen.conf");

    let contents = format!(
        "# Generated by christen route — routes this session through the agent namespace.\n\
         [Service]\n\
         ExecStart=\n\
         ExecStart=/home/jsy/.local/bin/agentns-claude --intent {intent} --budget {budget} -- {exec_start}\n"
    );

    DropIn { path, contents }
}

// ── SystemdSource ─────────────────────────────────────────────────────────────

/// Discovers launch sites by scanning a systemd user unit directory.
///
/// Only `.service` files whose `ExecStart=` line contains `claude` (as a
/// substring — covers `claude-build-headless.sh`, `claude` directly, etc.) are
/// returned as [`RawSite`]s. Additionally, a synthetic `ShellRc` site for the
/// interactive shell is always appended.
pub struct SystemdSource {
    /// The directory to scan (e.g. `~/.config/systemd/user`).
    pub dir: PathBuf,
}

impl SystemdSource {
    /// Create a new `SystemdSource` rooted at `dir`.
    #[must_use]
    pub const fn new(dir: PathBuf) -> Self {
        Self { dir }
    }
}

impl LaunchSiteSource for SystemdSource {
    fn sites(&self) -> Result<Vec<RawSite>, SourceError> {
        let mut sites: Vec<RawSite> = Vec::new();

        let entries = match fs::read_dir(&self.dir) {
            Ok(e) => e,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                // Directory absent → no systemd sites (not an error).
                return Ok(vec![shell_rc_site()]);
            }
            Err(e) => return Err(SourceError::Io(e)),
        };

        for entry in entries.flatten() {
            let path = entry.path();
            let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
                continue;
            };
            if !name.ends_with(".service") {
                continue;
            }
            let content = fs::read_to_string(&path).map_err(SourceError::Io)?;
            let exec_start = extract_exec_start(&content);
            // Only include units whose ExecStart references a claude executable.
            if !exec_start_references_claude(&exec_start) {
                continue;
            }
            sites.push(RawSite {
                id: name.to_owned(),
                kind: SiteKind::SystemdUnit {
                    unit: name.to_owned(),
                    exec_start: exec_start.clone(),
                },
                exec_line: exec_start,
            });
        }

        // Always append the interactive shell site.
        sites.push(shell_rc_site());

        Ok(sites)
    }
}

/// Extracts the value of the first `ExecStart=` line from a unit file.
fn extract_exec_start(content: &str) -> String {
    content
        .lines()
        .find(|l| l.trim_start().starts_with("ExecStart="))
        .and_then(|l| l.split_once('=').map(|x| x.1))
        .unwrap_or("")
        .to_owned()
}

/// Returns `true` if the `ExecStart` value references a `claude` binary.
fn exec_start_references_claude(exec_start: &str) -> bool {
    // Match `claude` as a word component in the path — covers:
    //   /usr/bin/claude, .../claude-build-headless.sh, agentns-claude, etc.
    exec_start.contains("claude")
}

/// Returns the synthetic interactive-shell `RawSite`.
fn shell_rc_site() -> RawSite {
    RawSite {
        id: "interactive".to_owned(),
        kind: SiteKind::ShellRc {
            path: dirs_next::home_dir()
                .unwrap_or_else(|| PathBuf::from("/home/jsy"))
                .join(".zshrc"),
        },
        exec_line: "claude".to_owned(),
    }
}

// ── Route application ─────────────────────────────────────────────────────────

/// Error type for route application failures.
#[derive(Debug, thiserror::Error)]
pub enum RouteError {
    /// An I/O error occurred while writing a drop-in.
    #[error("I/O error writing drop-in {path}: {source}")]
    Io {
        /// The drop-in path that failed.
        path: PathBuf,
        /// Underlying I/O error.
        #[source]
        source: std::io::Error,
    },
}

/// Applies (or prints) the route plan.
///
/// - `dry_run = true` — print what *would* be written; no filesystem writes.
/// - `dry_run = false` — write drop-ins and print (never run) reload lines.
/// - `unit_filter` — if `Some`, only process that unit.
///
/// # Errors
/// Returns [`RouteError`] if a drop-in file cannot be written (only in
/// `dry_run = false` mode).
pub fn apply_route<W: Write>(
    plan: &RoutePlan,
    config: &ChristenConfig,
    dry_run: bool,
    unit_filter: Option<&str>,
    out: &mut W,
) -> Result<(), RouteError> {
    let mut units_to_reload: Vec<String> = Vec::new();

    for action in &plan.actions {
        match action {
            RouteAction::Wire { site, from, to } => {
                // Parse unit name from the site id (it IS the unit name).
                let unit = site.as_str();
                if let Some(filter) = unit_filter {
                    if unit != filter {
                        continue;
                    }
                }

                // Derive intent from `to` line (everything after `--intent ` up to next space).
                let intent = extract_intent_from_to(to).unwrap_or("unknown");
                let budget = extract_budget_from_to(to).unwrap_or(&config.default_budget);

                let dropin = render_dropin(&config.systemd_dir, unit, from, intent, budget);

                if dry_run {
                    writeln_ignore(out, &format!("# Would write: {}", dropin.path.display()));
                    writeln_ignore(out, &dropin.contents);
                } else {
                    // Create the .d directory.
                    let parent = dropin.path.parent().ok_or_else(|| RouteError::Io {
                        path: dropin.path.clone(),
                        source: std::io::Error::new(
                            std::io::ErrorKind::InvalidInput,
                            "drop-in path has no parent",
                        ),
                    })?;
                    fs::create_dir_all(parent).map_err(|e| RouteError::Io {
                        path: parent.to_owned(),
                        source: e,
                    })?;
                    fs::write(&dropin.path, &dropin.contents).map_err(|e| RouteError::Io {
                        path: dropin.path.clone(),
                        source: e,
                    })?;
                    writeln_ignore(out, &format!("Wrote: {}", dropin.path.display()));
                    units_to_reload.push(unit.to_owned());
                }
            }
            RouteAction::Advise { site, snippet } => {
                if let Some(filter) = unit_filter {
                    if site != filter {
                        continue;
                    }
                }
                writeln_ignore(out, &format!("# Advise for {site}:"));
                writeln_ignore(out, snippet);
                writeln_ignore(out, "");
            }
            RouteAction::AlreadyWrapped { site } => {
                if let Some(filter) = unit_filter {
                    if site != filter {
                        continue;
                    }
                }
                writeln_ignore(out, &format!("# {site}: already wrapped — no change needed."));
            }
            RouteAction::Skip { site, reason } => {
                if let Some(filter) = unit_filter {
                    if site != filter {
                        continue;
                    }
                }
                writeln_ignore(out, &format!("# {site}: skipped — {reason}"));
            }
        }
    }

    if !dry_run && !units_to_reload.is_empty() {
        writeln_ignore(out, "");
        writeln_ignore(out, "# Run the following to activate the drop-ins (NOT run automatically):");
        writeln_ignore(out, "  systemctl --user daemon-reload");
        for unit in &units_to_reload {
            let svc = unit.strip_suffix(".service").unwrap_or(unit);
            writeln_ignore(out, &format!("  systemctl --user restart {svc}"));
        }
        writeln_ignore(out, "");
        writeln_ignore(
            out,
            "# NOTE: agentns-claude needs cap_sys_admin+ep to create the agent namespace.",
        );
        writeln_ignore(out, "#       Run `christen cap` to check and get the exact setcap command.");
    }

    Ok(())
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Extracts the `--intent <tag>` value from a Wire `to` line.
fn extract_intent_from_to(to: &str) -> Option<&str> {
    let idx = to.find("--intent ")?;
    let rest = &to[idx + "--intent ".len()..];
    Some(rest.split_whitespace().next().unwrap_or("unknown"))
}

/// Extracts the `--budget <spec>` value from a Wire `to` line.
fn extract_budget_from_to(to: &str) -> Option<&str> {
    let idx = to.find("--budget ")?;
    let rest = &to[idx + "--budget ".len()..];
    Some(rest.split_whitespace().next().unwrap_or(""))
}

/// Write a line, ignoring broken-pipe errors.
fn writeln_ignore<W: Write>(w: &mut W, line: &str) {
    let _ = writeln!(w, "{line}");
}

// Re-export Write so callers don't need to import it separately.
use std::io::Write;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_dropin_pure_no_fs_calls() {
        // render_dropin must not touch the filesystem — we call it and assert
        // the returned value is correct without creating any temp dir.
        let dir = Path::new("/tmp/fake-systemd");
        let dropin = render_dropin(
            dir,
            "claude-build.service",
            "/home/jsy/.local/bin/claude-build-headless.sh",
            "/build",
            "wall=7200s,fork=2000",
        );
        assert_eq!(
            dropin.path,
            dir.join("claude-build.service.d/10-christen.conf"),
        );
        // Must contain the clear-then-set pair in order.
        let lines: Vec<&str> = dropin.contents.lines().collect();
        let clear_pos = lines.iter().position(|l| *l == "ExecStart=");
        let set_pos = lines
            .iter()
            .position(|l| l.starts_with("ExecStart=/home/jsy/.local/bin/agentns-claude"));
        assert!(clear_pos.is_some(), "must have clear ExecStart= line");
        assert!(set_pos.is_some(), "must have set ExecStart= line");
        assert!(
            clear_pos.unwrap() < set_pos.unwrap(),
            "clear must come before set"
        );
    }

    #[test]
    fn render_dropin_contains_intent_and_budget() {
        let dropin = render_dropin(
            Path::new("/tmp/sd"),
            "claude-dream.service",
            "/home/jsy/.local/bin/claude-dream-headless.sh",
            "/dream",
            "wall=3600s,fork=500",
        );
        assert!(dropin.contents.contains("--intent /dream"));
        assert!(dropin.contents.contains("--budget wall=3600s,fork=500"));
        assert!(dropin.contents.contains("claude-dream-headless.sh"));
    }
}
